/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apicativo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.validator.GenericValidator;

/**
 *
 * @author carle
 */
public class TelaHistorico extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form TelaHistorico
     */
    public TelaHistorico() {
        initComponents();
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.addColumn("ID");
        modelo.addColumn("Colmeia");
        modelo.addColumn("Manejo");
        modelo.addColumn("Tecnico");
        modelo.addColumn("Data");
        modelo.addColumn("Observacoes");
        tabela.setModel(modelo);
        carregarCombos();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbColmeia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbManejo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbTecnico = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDaColmeia = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtId.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historico de operações");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("ID:");

        jLabel2.setText("Colmeia:");

        cmbColmeia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel5.setText("Manejo:");

        cmbManejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel6.setText("Tecnico:");

        cmbTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel3.setText("Data (dd/mm/aaaa):");

        jLabel8.setText("Observacoes:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar ID");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDaColmeia.setText("Da colmeia");
        btnDaColmeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaColmeiaActionPerformed(evt);
            }
        });

        btnListar.setText("Listar todos");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbColmeia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                    )
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDaColmeia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    )
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                )
                .addContainerGap()
            )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbColmeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbManejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnBuscar)
                    .addComponent(btnDaColmeia)
                    .addComponent(btnListar)
                    .addComponent(btnLimpar)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap()
            )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDaColmeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaColmeiaActionPerformed
        listarDaColmeia();
    }//GEN-LAST:event_btnDaColmeiaActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int linha = tabela.getSelectedRow();
        txtId.setText(modelo.getValueAt(linha, 0).toString());
        cmbColmeia.setSelectedItem(modelo.getValueAt(linha, 1).toString());
        cmbManejo.setSelectedItem(modelo.getValueAt(linha, 2).toString());
        cmbTecnico.setSelectedItem(modelo.getValueAt(linha, 3).toString());
        txtData.setText(modelo.getValueAt(linha, 4).toString());
        txtObs.setText(modelo.getValueAt(linha, 5).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    // carrega as colmeias, manejos e tecnicos nos combos
    public void carregarCombos() {
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT * FROM colmeia ORDER BY id_colmeia");
            cmbColmeia.removeAllItems();
            while (rs.next()) {
                cmbColmeia.addItem(rs.getInt("id_colmeia") + " - " + rs.getString("codigo_identificador"));
            }

            rs = st.executeQuery("SELECT * FROM manejo ORDER BY id_manejo");
            cmbManejo.removeAllItems();
            while (rs.next()) {
                cmbManejo.addItem(rs.getInt("id_manejo") + " - " + rs.getString("tipo_procedimento"));
            }

            rs = st.executeQuery("SELECT * FROM tecnico ORDER BY id_tecnico");
            cmbTecnico.removeAllItems();
            while (rs.next()) {
                cmbTecnico.addItem(rs.getInt("id_tecnico") + " - " + rs.getString("nome"));
            }

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e.getMessage());
        }
    }

    public void salvar() {
        if (cmbColmeia.getSelectedItem() == null || cmbManejo.getSelectedItem() == null || cmbTecnico.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Precisa ter colmeia, manejo e tecnico cadastrados!");
            return;
        }
        if (GenericValidator.isBlankOrNull(txtData.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha a data!");
            return;
        }
        if (!GenericValidator.isDate(txtData.getText(), "dd/MM/yyyy", true)) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        String data = "";
        try {
            SimpleDateFormat f1 = new SimpleDateFormat("dd/MM/yyyy");
            f1.setLenient(false);
            SimpleDateFormat f2 = new SimpleDateFormat("yyyy-MM-dd");
            data = f2.format(f1.parse(txtData.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        if (txtObs.getText().length() > 255) {
            JOptionPane.showMessageDialog(null, "Observacao muito grande! Maximo 255 caracteres");
            return;
        }
        String idColmeia = cmbColmeia.getSelectedItem().toString().split(" - ")[0];
        String idManejo = cmbManejo.getSelectedItem().toString().split(" - ")[0];
        String idTecnico = cmbTecnico.getSelectedItem().toString().split(" - ")[0];
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            String sql = "INSERT INTO colmeia_manejo (id_colmeia, id_manejo, data_realizacao, observacoes, id_tecnico) VALUES ("
                    + idColmeia + ", " + idManejo + ", '" + data + "', '" + txtObs.getText() + "', " + idTecnico + ")";
            System.out.println(sql);
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(null, "Manejo registrado no historico!");
            limpar();
            listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + e.getMessage());
        }
    }

    public void editar() {
        if (GenericValidator.isBlankOrNull(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um registro na tabela ou digite o ID!");
            return;
        }
        if (!GenericValidator.isInt(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "O ID tem que ser um numero!");
            return;
        }
        if (GenericValidator.isBlankOrNull(txtData.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha a data!");
            return;
        }
        if (!GenericValidator.isDate(txtData.getText(), "dd/MM/yyyy", true)) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        String data = "";
        try {
            SimpleDateFormat f1 = new SimpleDateFormat("dd/MM/yyyy");
            f1.setLenient(false);
            SimpleDateFormat f2 = new SimpleDateFormat("yyyy-MM-dd");
            data = f2.format(f1.parse(txtData.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        String idColmeia = cmbColmeia.getSelectedItem().toString().split(" - ")[0];
        String idManejo = cmbManejo.getSelectedItem().toString().split(" - ")[0];
        String idTecnico = cmbTecnico.getSelectedItem().toString().split(" - ")[0];
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            String sql = "UPDATE colmeia_manejo SET id_colmeia = " + idColmeia + ", id_manejo = " + idManejo + ", data_realizacao = '" + data
                    + "', observacoes = '" + txtObs.getText() + "', id_tecnico = " + idTecnico + " WHERE id_colmeia_manejo = " + txtId.getText();
            System.out.println(sql);
            int linhas = st.executeUpdate(sql);
            con.close();
            if (linhas > 0) {
                JOptionPane.showMessageDialog(null, "Registro atualizado!");
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum registro encontrado com esse ID");
            }
            limpar();
            listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao editar: " + e.getMessage());
        }
    }

    public void excluir() {
        if (GenericValidator.isBlankOrNull(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione um registro na tabela ou digite o ID!");
            return;
        }
        if (!GenericValidator.isInt(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "O ID tem que ser um numero!");
            return;
        }
        int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o registro " + txtId.getText() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                Connection con = Conexao.conectar();
                Statement st = con.createStatement();
                String sql = "DELETE FROM colmeia_manejo WHERE id_colmeia_manejo = " + txtId.getText();
                st.executeUpdate(sql);
                con.close();
                JOptionPane.showMessageDialog(null, "Registro excluido!");
                limpar();
                listar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
            }
        }
    }

    public void buscar() {
        if (GenericValidator.isBlankOrNull(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o ID pra buscar!");
            return;
        }
        if (!GenericValidator.isInt(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "O ID tem que ser um numero!");
            return;
        }
        carregarTabela("SELECT * FROM colmeia_manejo WHERE id_colmeia_manejo = " + txtId.getText());
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Registro nao encontrado");
        }
    }

    // mostra so os manejos da colmeia escolhida no combo
    public void listarDaColmeia() {
        if (cmbColmeia.getSelectedItem() == null) {
            return;
        }
        String idColmeia = cmbColmeia.getSelectedItem().toString().split(" - ")[0];
        carregarTabela("SELECT * FROM colmeia_manejo WHERE id_colmeia = " + idColmeia + " ORDER BY data_realizacao DESC");
    }

    public void listar() {
        carregarTabela("SELECT * FROM colmeia_manejo ORDER BY data_realizacao DESC");
    }

    public void carregarTabela(String sql) {
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            modelo.setRowCount(0);
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            while (rs.next()) {
                // busca o nome de cada coisa
                String colmeia = "";
                Statement st2 = con.createStatement();
                ResultSet rs2 = st2.executeQuery("SELECT * FROM colmeia WHERE id_colmeia = " + rs.getInt("id_colmeia"));
                if (rs2.next()) {
                    colmeia = rs2.getInt("id_colmeia") + " - " + rs2.getString("codigo_identificador");
                }

                String manejo = "";
                Statement st3 = con.createStatement();
                ResultSet rs3 = st3.executeQuery("SELECT * FROM manejo WHERE id_manejo = " + rs.getInt("id_manejo"));
                if (rs3.next()) {
                    manejo = rs3.getInt("id_manejo") + " - " + rs3.getString("tipo_procedimento");
                }

                String tecnico = "";
                Statement st4 = con.createStatement();
                ResultSet rs4 = st4.executeQuery("SELECT * FROM tecnico WHERE id_tecnico = " + rs.getInt("id_tecnico"));
                if (rs4.next()) {
                    tecnico = rs4.getInt("id_tecnico") + " - " + rs4.getString("nome");
                }

                String obs = rs.getString("observacoes");
                if (obs == null) {
                    obs = "";
                }
                modelo.addRow(new Object[]{rs.getInt("id_colmeia_manejo"), colmeia, manejo, tecnico, f.format(rs.getDate("data_realizacao")), obs});
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar: " + e.getMessage());
        }
    }

    public void limpar() {
        txtId.setText("");
        txtData.setText("");
        txtObs.setText("");
        if (cmbColmeia.getItemCount() > 0) {
            cmbColmeia.setSelectedIndex(0);
        }
        if (cmbManejo.getItemCount() > 0) {
            cmbManejo.setSelectedIndex(0);
        }
        if (cmbTecnico.getItemCount() > 0) {
            cmbTecnico.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDaColmeia;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbColmeia;
    private javax.swing.JComboBox<String> cmbManejo;
    private javax.swing.JComboBox<String> cmbTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtObs;
    // End of variables declaration//GEN-END:variables
}
