/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apicativo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author carle
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnColmeias = new javax.swing.JButton();
        btnManejos = new javax.swing.JButton();
        btnTecnicos = new javax.swing.JButton();
        btnLocalizacoes = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ApiCativo");
        jLabel1.setToolTipText("O sistema para apicultores!");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnColmeias.setText("Colmeias");
        btnColmeias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColmeiasActionPerformed(evt);
            }
        });

        btnManejos.setText("Manejos / Procedimentos");
        btnManejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManejosActionPerformed(evt);
            }
        });

        btnTecnicos.setText("Tecnicos");
        btnTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecnicosActionPerformed(evt);
            }
        });

        btnLocalizacoes.setText("Localizações / Setores");
        btnLocalizacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizacoesActionPerformed(evt);
            }
        });

        btnHistorico.setText("Historico de Manejos");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Relatorio");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnTecnicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnManejos))
                    .addComponent(btnColmeias, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnColmeias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLocalizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManejos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColmeiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColmeiasActionPerformed
        new TelaColmeia().setVisible(true);
    }//GEN-LAST:event_btnColmeiasActionPerformed

    private void btnTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecnicosActionPerformed
        new TelaTecnico().setVisible(true);
    }//GEN-LAST:event_btnTecnicosActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        new TelaHistorico().setVisible(true);
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void btnLocalizacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizacoesActionPerformed
        new TelaLocalizacao().setVisible(true);
    }//GEN-LAST:event_btnLocalizacoesActionPerformed

    private void btnManejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManejosActionPerformed
        new TelaManejo().setVisible(true);
    }//GEN-LAST:event_btnManejosActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        gerarRelatorio();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    public void gerarRelatorio() {
        StringBuilder relatorio = new StringBuilder();
        try {
            Connection conexao = Conexao.conectar();
            relatorio.append(montarTotalDeColmeias(conexao));
            relatorio.append(montarColmeiasPorStatus(conexao));
            relatorio.append(montarSetoresComMaisDeUmaColmeia(conexao));
            relatorio.append(montarUltimoManejo(conexao));
            conexao.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatorio: " + e.getMessage());
            return;
        }
        mostrarRelatorio(relatorio.toString());
    }

    private String montarTotalDeColmeias(Connection conexao) throws SQLException {
        ResultSet resultado = conexao.createStatement().executeQuery("SELECT COUNT(*) FROM colmeia");
        resultado.next();
        return "Total de colmeias: " + resultado.getInt(1) + "\n\n";
    }

    private String montarColmeiasPorStatus(Connection conexao) throws SQLException {
        StringBuilder texto = new StringBuilder("Colmeias por status:\n");
        ResultSet resultado = conexao.createStatement().executeQuery(
                "SELECT status, COUNT(*) AS quantidade FROM colmeia GROUP BY status ORDER BY quantidade DESC");
        while (resultado.next()) {
            texto.append("  ").append(resultado.getString("status"))
                    .append(": ").append(resultado.getInt("quantidade")).append("\n");
        }
        return texto.append("\n").toString();
    }

    private String montarSetoresComMaisDeUmaColmeia(Connection conexao) throws SQLException {
        StringBuilder texto = new StringBuilder("Setores com mais de 1 colmeia:\n");
        ResultSet resultado = conexao.createStatement().executeQuery(
                "SELECT l.nome_setor, COUNT(c.id_colmeia) AS quantidade FROM localizacao l "
                + "JOIN colmeia c ON c.id_localizacao = l.id_localizacao "
                + "GROUP BY l.nome_setor HAVING COUNT(c.id_colmeia) > 1");
        boolean encontrouSetor = false;
        while (resultado.next()) {
            texto.append("  ").append(resultado.getString("nome_setor"))
                    .append(": ").append(resultado.getInt("quantidade")).append(" colmeias\n");
            encontrouSetor = true;
        }
        if (!encontrouSetor) {
            texto.append("  nenhum\n");
        }
        return texto.append("\n").toString();
    }

    private String montarUltimoManejo(Connection conexao) throws SQLException {
        ResultSet resultado = conexao.createStatement().executeQuery(
                "SELECT * FROM vw_historico_completo ORDER BY data_realizacao DESC LIMIT 1");
        if (!resultado.next()) {
            return "Nenhum manejo registrado ainda\n";
        }
        return "Ultimo manejo realizado:\n  "
                + ConversorData.paraTela(resultado.getDate("data_realizacao")) + " - "
                + resultado.getString("tipo_procedimento") + " na colmeia "
                + resultado.getString("codigo_identificador") + " (" + resultado.getString("nome_setor") + ") por "
                + resultado.getString("tecnico") + "\n";
    }

    private void mostrarRelatorio(String texto) {
        JTextArea areaRelatorio = new JTextArea(texto);
        areaRelatorio.setEditable(false);
        JOptionPane.showMessageDialog(null, areaRelatorio, "Relatorio ApiCativo", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColmeias;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnLocalizacoes;
    private javax.swing.JButton btnManejos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnTecnicos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
