/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apicativo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.validator.GenericValidator;

/**
 *
 * @author carle
 */
public class TelaColmeia extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form TelaColmeia
     */
    public TelaColmeia() {
        initComponents();
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Codigo");
        modelo.addColumn("Data instalacao");
        modelo.addColumn("Status");
        modelo.addColumn("Tamanho");
        modelo.addColumn("Estilo");
        modelo.addColumn("Localizacao");
        tabela.setModel(modelo);
        carregarLocalizacoes();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbLocal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbTamanho = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbEstilo = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Colmeias");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("ID:");

        jLabel5.setText("Codigo:");

        jLabel2.setText("Data instalacao (dd/mm/aaaa):");

        jLabel3.setText("Localizacao:");

        cmbLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel6.setText("Status:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativa", "Inativa", "Enxameou", "Morta" }));

        jLabel7.setText("Tamanho caixa:");

        cmbTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninho", "Ninho + 1 melgueira", "Ninho + 2 melgueiras", "Nucleo" }));

        jLabel9.setText("Estilo caixa:");

        cmbEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Langstroth", "Schenk", "Top Bar", "Dadant" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar todos");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                    )
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    )
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                )
                .addContainerGap()
            )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnBuscar)
                    .addComponent(btnListar)
                    .addComponent(btnLimpar)
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap()
            )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int linha = tabela.getSelectedRow();
        txtId.setText(modelo.getValueAt(linha, 0).toString());
        txtCodigo.setText(modelo.getValueAt(linha, 1).toString());
        txtData.setText(modelo.getValueAt(linha, 2).toString());
        cmbStatus.setSelectedItem(modelo.getValueAt(linha, 3).toString());
        cmbTamanho.setSelectedItem(modelo.getValueAt(linha, 4).toString());
        cmbEstilo.setSelectedItem(modelo.getValueAt(linha, 5).toString());
        cmbLocal.setSelectedItem(modelo.getValueAt(linha, 6).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    public void carregarLocalizacoes() {
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM localizacao ORDER BY id_localizacao");
            cmbLocal.removeAllItems();
            while (rs.next()) {
                cmbLocal.addItem(rs.getInt("id_localizacao") + " - " + rs.getString("nome_setor"));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar localizacoes: " + e.getMessage());
        }
    }

    public void salvar() {
        if (GenericValidator.isBlankOrNull(txtCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha o codigo da colmeia!");
            return;
        }
        if (!GenericValidator.maxLength(txtCodigo.getText(), 50)) {
            JOptionPane.showMessageDialog(null, "Texto muito grande! Maximo 50 caracteres");
            return;
        }
        if (GenericValidator.isBlankOrNull(txtData.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha a data de instalacao!");
            return;
        }
        if (!GenericValidator.isDate(txtData.getText(), "dd/MM/yyyy", true)) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        if (cmbLocal.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Cadastre uma localizacao antes!");
            return;
        }
        String data = "";
        try {
            SimpleDateFormat f1 = new SimpleDateFormat("dd/MM/yyyy");
            f1.setLenient(false);
            SimpleDateFormat f2 = new SimpleDateFormat("yyyy-MM-dd");
            data = f2.format(f1.parse(txtData.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        String idLocal = cmbLocal.getSelectedItem().toString().split(" - ")[0];
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            String sql = "INSERT INTO colmeia (codigo_identificador, data_instalacao, status, tamanho_caixa, estilo_caixa, id_localizacao) VALUES ('"
                    + txtCodigo.getText() + "', '" + data + "', '" + cmbStatus.getSelectedItem() + "', '" + cmbTamanho.getSelectedItem() + "', '"
                    + cmbEstilo.getSelectedItem() + "', " + idLocal + ")";
            System.out.println(sql);
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(null, "Colmeia salva com sucesso!");
            limpar();
            listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar (o codigo pode ja existir): " + e.getMessage());
        }
    }

    public void editar() {
        if (GenericValidator.isBlankOrNull(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione uma colmeia na tabela ou digite o ID!");
            return;
        }
        if (!GenericValidator.isInt(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "O ID tem que ser um numero!");
            return;
        }
        if (GenericValidator.isBlankOrNull(txtCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha o codigo da colmeia!");
            return;
        }
        if (!GenericValidator.maxLength(txtCodigo.getText(), 50)) {
            JOptionPane.showMessageDialog(null, "Texto muito grande! Maximo 50 caracteres");
            return;
        }
        if (GenericValidator.isBlankOrNull(txtData.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha a data de instalacao!");
            return;
        }
        if (!GenericValidator.isDate(txtData.getText(), "dd/MM/yyyy", true)) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        String data = "";
        try {
            SimpleDateFormat f1 = new SimpleDateFormat("dd/MM/yyyy");
            f1.setLenient(false);
            SimpleDateFormat f2 = new SimpleDateFormat("yyyy-MM-dd");
            data = f2.format(f1.parse(txtData.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data invalida! Use dd/mm/aaaa");
            return;
        }
        String idLocal = cmbLocal.getSelectedItem().toString().split(" - ")[0];
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            String sql = "UPDATE colmeia SET codigo_identificador = '" + txtCodigo.getText() + "', data_instalacao = '" + data
                    + "', status = '" + cmbStatus.getSelectedItem() + "', tamanho_caixa = '" + cmbTamanho.getSelectedItem()
                    + "', estilo_caixa = '" + cmbEstilo.getSelectedItem() + "', id_localizacao = " + idLocal
                    + " WHERE id_colmeia = " + txtId.getText();
            System.out.println(sql);
            int linhas = st.executeUpdate(sql);
            con.close();
            if (linhas > 0) {
                JOptionPane.showMessageDialog(null, "Colmeia atualizada!");
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma colmeia encontrada com esse ID");
            }
            limpar();
            listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao editar: " + e.getMessage());
        }
    }

    public void excluir() {
        if (GenericValidator.isBlankOrNull(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione uma colmeia na tabela ou digite o ID!");
            return;
        }
        if (!GenericValidator.isInt(txtId.getText())) {
            JOptionPane.showMessageDialog(null, "O ID tem que ser um numero!");
            return;
        }
        int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir a colmeia " + txtId.getText() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                Connection con = Conexao.conectar();
                Statement st = con.createStatement();
                String sql = "DELETE FROM colmeia WHERE id_colmeia = " + txtId.getText();
                st.executeUpdate(sql);
                con.close();
                JOptionPane.showMessageDialog(null, "Colmeia excluida!");
                limpar();
                listar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nao foi possivel excluir, a colmeia tem manejos no historico.\n" + e.getMessage());
            }
        }
    }

    // busca pelo codigo, se nao tiver codigo busca pelo id
    public void buscar() {
        String sql = "";
        if (!GenericValidator.isBlankOrNull(txtCodigo.getText())) {
            sql = "SELECT * FROM colmeia WHERE codigo_identificador ILIKE '%" + txtCodigo.getText() + "%' ORDER BY id_colmeia";
        } else if (!GenericValidator.isBlankOrNull(txtId.getText())) {
            sql = "SELECT * FROM colmeia WHERE id_colmeia = " + txtId.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Digite o codigo ou o ID pra buscar!");
            return;
        }
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            modelo.setRowCount(0);
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            int cont = 0;
            while (rs.next()) {
                // pega o nome da localizacao
                String local = "";
                Statement st2 = con.createStatement();
                ResultSet rs2 = st2.executeQuery("SELECT * FROM localizacao WHERE id_localizacao = " + rs.getInt("id_localizacao"));
                if (rs2.next()) {
                    local = rs2.getInt("id_localizacao") + " - " + rs2.getString("nome_setor");
                }
                String data = "";
                if (rs.getDate("data_instalacao") != null) {
                    data = f.format(rs.getDate("data_instalacao"));
                }
                modelo.addRow(new Object[]{rs.getInt("id_colmeia"), rs.getString("codigo_identificador"), data, rs.getString("status"),
                    rs.getString("tamanho_caixa"), rs.getString("estilo_caixa"), local});
                cont++;
            }
            con.close();
            if (cont == 0) {
                JOptionPane.showMessageDialog(null, "Nenhuma colmeia encontrada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar: " + e.getMessage());
        }
    }

    public void listar() {
        try {
            Connection con = Conexao.conectar();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM colmeia ORDER BY id_colmeia");
            modelo.setRowCount(0);
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            while (rs.next()) {
                // pega o nome da localizacao
                String local = "";
                Statement st2 = con.createStatement();
                ResultSet rs2 = st2.executeQuery("SELECT * FROM localizacao WHERE id_localizacao = " + rs.getInt("id_localizacao"));
                if (rs2.next()) {
                    local = rs2.getInt("id_localizacao") + " - " + rs2.getString("nome_setor");
                }
                String data = "";
                if (rs.getDate("data_instalacao") != null) {
                    data = f.format(rs.getDate("data_instalacao"));
                }
                modelo.addRow(new Object[]{rs.getInt("id_colmeia"), rs.getString("codigo_identificador"), data, rs.getString("status"),
                    rs.getString("tamanho_caixa"), rs.getString("estilo_caixa"), local});
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar: " + e.getMessage());
        }
    }

    public void limpar() {
        txtId.setText("");
        txtCodigo.setText("");
        txtData.setText("");
        cmbStatus.setSelectedIndex(0);
        cmbTamanho.setSelectedIndex(0);
        cmbEstilo.setSelectedIndex(0);
        if (cmbLocal.getItemCount() > 0) {
            cmbLocal.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaColmeia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaColmeia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaColmeia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaColmeia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaColmeia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbEstilo;
    private javax.swing.JComboBox<String> cmbLocal;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
